apiVersion: v1
kind: Service
metadata:
  labels:
    app: demochat-master
  name: demochat-master
spec:
  type: NodePort
  ports:
  - name: "http"
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    service: demochat-board
