---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-chat
  labels:
    service: demo-chat
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: demo-chat
    spec:
      containers:
      - image: sreedocker123/demochatmaster:latest
        name: app
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
