apiVersion: v1
kind: Service
metadata:
  labels:
    app: demochat-master
  name: demochat-master
spec:
  type: NodePort
  ports:
  - name: "http"
    port: 5000
    protocol: TCP
    targetPort: 8080
  selector:
    service: demochat-board
